### ISSUE TITLE
have a error on run script 

### ISSUE THREAD

**Issue by reedniv** [desci/tg-cryptoforexbot#12]
Traceback (most recent call last):
  File "./start.py", line 13, in <module>
    from cryptoforexbot.bot import cryptoforex as cryptoforexbot
  File "/data/data/com.termux/files/home/tg-cryptoforexbot/cryptoforexbot/bot.py", line 12
    print 'You have to `pip install telepot`. Try again when you do. You can do `pip install -r requirements.txt`.'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('You have to `pip install telepot`. Try again when you do. You can do `pip install -r requirements.txt`.')?

**I using ./start.py or python start.py same problem**

**Comment by iuriguilherme** [comment]
You're using python3. This version will only work on python2.

Attempt to `python2 start.py`

**Comment by reedniv** [comment]
> You're using python3. This version will only work on python2.
> 
> Attempt to `python2 start.py`

**Thanks before, fixed error.** 


How about error after run this bot

I have like this



`[2020-01-18 20:02:35.806531] RCV: Received "{u'reply_to_message': {u'date': 1579352534, u'text': u'[2020-01-18 20:02:13.253918] RCV: Received "{u\'from\': {u\'username\': u\'REDACTED\', u\'first_name\': u\'REDACTED\', u\'is_bot\': False, u\'id\': REDACTED, u\'language_code\': u\'id\'}, u\'new_chat_participant\': {u\'username\': u\'REDACTED\', u\'first_name\': u\'REDACTED\', u\'is_bot\': True, u\'id\': REDACTED}, u\'new_chat_members\': [{u\'username\': u\'REDACTED\', u\'first_name\': u\'REDACTED\', u\'is_bot\': True, u\'id\': REDACTED}], u\'chat\': {u\'type\': u\'supergroup\', u\'id\': REDACTED, u\'title\': u\'REDACTED\'}, u\'date\': 1579352533, u\'message_id\': REDACTED, u\'new_chat_member\': {u\'username\': u\'REDACTED\', u\'first_name\': u\'REDACTED\', u\'is_bot\': True, u\'id\': REDACTED}}" from REDACTED', u'from': {u'username': u'REDACTED', u'first_name': u'REDACTED', u'is_bot': True, u'id': REDACTED}, u'message_id': REDACTED, u'chat': {u'type': u'supergroup', u'id': REDACTED, u'title': u'REDACTED'}}, u'text': u'/feedback', u'entities': [{u'length': 9, u'type': u'bot_command', u'offset': 0}], u'chat': {u'type': u'supergroup', u'id': REDACTED, u'title': u'REDACTED'}, u'date': 1579352554, u'from': {u'username': u'REDACTED', u'first_name': u'REDACTED', u'is_bot': False, u'id': REDACTED, u'language_code': u'id'}, u'message_id': REDACTED}" from REDACTED`

**Comment by iuriguilherme** [comment]
That is unrelated to this issue, it has been addressed on #13 

I have redacted personal information on that log.

**Comment by iuriguilherme** [comment]
Logging improved on b81f922e7cb768f1f914bf3c84a465e3f9acbebc

TODO: Update codebase to python3 also use file logging
